plugins {
    id 'java'
    id 'war'
}

group 'com.codegym'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    tasks.withType(JavaCompile) {
        options.compilerArgs << '-parameters'
    }
}

dependencies {
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    implementation 'org.springframework:spring-webmvc:6.0.13'
    implementation 'org.springframework:spring-orm:6.0.13'
    implementation 'org.springframework:spring-tx:6.0.13'
    implementation 'org.hibernate.orm:hibernate-core:6.2.7.Final'
    implementation 'com.mysql:mysql-connector-j:8.0.33'
    implementation 'org.springframework.data:spring-data-jpa:3.4.2'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
}

test {
    useJUnitPlatform()
}

war {
    archiveFileName = "${project.name}.war"
}